apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rgilv5ffa-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rgilv5ffa-nodejs 
  name: rgilv5ffa-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: rgilv5ffa-nodejs 
